parameters:
  client_name: "*Client"
  client_path: github.com/example
  path_to_generated: main/
  fields:
    - name: access_token
      type: string
    - name: login
      type: string
    - name: time_interval
      type: time.Duration
    - name: email
      type: string
    - name: password
      type: string
    - name: device_id
      type: string
    - name: referral_code
      type: string
    - name: reg_token
      type: string
    - name: reg_code
      type: string
    - name: tickers
      type: "[]string"
    - name: time
      type: time.Time
